"""
MCP Detection Rules Engine
Real-time detection of suspicious MCP tool usage patterns
"""

from pydantic import BaseModel, Field
from typing import List, Dict, Optional, Callable
from enum import Enum
from datetime import datetime
import re
import structlog

logger = structlog.get_logger()


class DetectionSeverity(str, Enum):
    """Severity of detection alert"""
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    INFO = "info"


class DetectionAlert(BaseModel):
    """Alert generated by detection rule"""
    rule_id: str
    rule_name: str
    severity: DetectionSeverity
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    description: str
    evidence: List[str] = Field(default_factory=list)
    affected_component: str
    recommended_action: str
    metadata: Dict = Field(default_factory=dict)


class MCPToolCall(BaseModel):
    """Record of an MCP tool invocation"""
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    agent_id: str
    tool_name: str
    parameters: Dict
    response: Optional[Dict] = None
    success: bool = True
    error: Optional[str] = None


class DetectionRule:
    """Base class for detection rules"""

    def __init__(
        self,
        rule_id: str,
        rule_name: str,
        severity: DetectionSeverity,
        description: str,
        recommended_action: str
    ):
        self.rule_id = rule_id
        self.rule_name = rule_name
        self.severity = severity
        self.description = description
        self.recommended_action = recommended_action

    def evaluate(self, tool_call: MCPToolCall, history: List[MCPToolCall]) -> Optional[DetectionAlert]:
        """
        Evaluate rule against tool call and history

        Args:
            tool_call: Current tool call to evaluate
            history: Recent tool call history

        Returns:
            DetectionAlert if rule triggers, None otherwise
        """
        raise NotImplementedError("Subclasses must implement evaluate()")


class SensitiveFileAccessRule(DetectionRule):
    """Detect access to sensitive files"""

    SENSITIVE_PATTERNS = [
        r'\.env$',
        r'\.aws/credentials$',
        r'\.ssh/id_rsa$',
        r'\.ssh/id_ed25519$',
        r'secrets\.json$',
        r'credentials\.json$',
        r'/etc/passwd$',
        r'/etc/shadow$',
        r'web\.config$',
        r'database\.yml$',
        r'\.git/config$'
    ]

    def __init__(self):
        super().__init__(
            rule_id="MCP-001",
            rule_name="Sensitive File Access Detection",
            severity=DetectionSeverity.CRITICAL,
            description="Detected attempt to access sensitive files containing credentials or secrets",
            recommended_action="Block file access and investigate agent prompt for potential injection"
        )

    def evaluate(self, tool_call: MCPToolCall, history: List[MCPToolCall]) -> Optional[DetectionAlert]:
        if 'filesystem' not in tool_call.tool_name.lower():
            return None

        # Check file path parameter
        file_path = tool_call.parameters.get('path', '') or tool_call.parameters.get('file_path', '')

        for pattern in self.SENSITIVE_PATTERNS:
            if re.search(pattern, file_path, re.IGNORECASE):
                return DetectionAlert(
                    rule_id=self.rule_id,
                    rule_name=self.rule_name,
                    severity=self.severity,
                    description=f"Attempt to access sensitive file: {file_path}",
                    evidence=[
                        f"Tool: {tool_call.tool_name}",
                        f"File path: {file_path}",
                        f"Agent: {tool_call.agent_id}",
                        f"Pattern matched: {pattern}"
                    ],
                    affected_component=tool_call.agent_id,
                    recommended_action=self.recommended_action,
                    metadata={
                        "file_path": file_path,
                        "tool_name": tool_call.tool_name,
                        "matched_pattern": pattern
                    }
                )

        return None


class PathTraversalRule(DetectionRule):
    """Detect path traversal attempts"""

    def __init__(self):
        super().__init__(
            rule_id="MCP-002",
            rule_name="Path Traversal Detection",
            severity=DetectionSeverity.CRITICAL,
            description="Detected path traversal attempt in file path parameter",
            recommended_action="Block request and sanitize file path inputs"
        )

    def evaluate(self, tool_call: MCPToolCall, history: List[MCPToolCall]) -> Optional[DetectionAlert]:
        if 'filesystem' not in tool_call.tool_name.lower():
            return None

        file_path = tool_call.parameters.get('path', '') or tool_call.parameters.get('file_path', '')

        # Check for path traversal patterns
        if '../' in file_path or '..\\' in file_path:
            return DetectionAlert(
                rule_id=self.rule_id,
                rule_name=self.rule_name,
                severity=self.severity,
                description=f"Path traversal detected: {file_path}",
                evidence=[
                    f"File path contains '../' or '..\\'",
                    f"Tool: {tool_call.tool_name}",
                    f"Parameter: {file_path}"
                ],
                affected_component=tool_call.agent_id,
                recommended_action=self.recommended_action,
                metadata={"file_path": file_path}
            )

        return None


class CommandInjectionRule(DetectionRule):
    """Detect command injection in parameters"""

    INJECTION_PATTERNS = [
        r';\s*\w+',  # ; command
        r'\|\s*\w+',  # | command
        r'&&\s*\w+',  # && command
        r'\$\(.*\)',  # $(command)
        r'`.*`',      # `command`
        r'>\s*/dev/',  # redirect
        r'<\s*\(',    # process substitution
    ]

    def __init__(self):
        super().__init__(
            rule_id="MCP-003",
            rule_name="Command Injection Detection",
            severity=DetectionSeverity.CRITICAL,
            description="Detected potential command injection in tool parameters",
            recommended_action="Block execution and sanitize inputs"
        )

    def evaluate(self, tool_call: MCPToolCall, history: List[MCPToolCall]) -> Optional[DetectionAlert]:
        # Check all string parameters
        for key, value in tool_call.parameters.items():
            if isinstance(value, str):
                for pattern in self.INJECTION_PATTERNS:
                    if re.search(pattern, value):
                        return DetectionAlert(
                            rule_id=self.rule_id,
                            rule_name=self.rule_name,
                            severity=self.severity,
                            description=f"Command injection detected in parameter '{key}'",
                            evidence=[
                                f"Parameter: {key}",
                                f"Value: {value}",
                                f"Pattern matched: {pattern}",
                                f"Tool: {tool_call.tool_name}"
                            ],
                            affected_component=tool_call.agent_id,
                            recommended_action=self.recommended_action,
                            metadata={
                                "parameter": key,
                                "value": value,
                                "pattern": pattern
                            }
                        )

        return None


class ToolChainingRule(DetectionRule):
    """Detect suspicious tool chaining patterns"""

    DANGEROUS_CHAINS = [
        (['filesystem_read', 'database_read', 'web_search'], ['network_request', 'api_call', 'web_fetch']),
        (['database_query'], ['filesystem_write', 'code_execution']),
        (['web_search', 'web_fetch'], ['code_execution', 'shell_command'])
    ]

    def __init__(self):
        super().__init__(
            rule_id="MCP-004",
            rule_name="Suspicious Tool Chaining Detection",
            severity=DetectionSeverity.HIGH,
            description="Detected suspicious sequence of tool calls indicating potential attack",
            recommended_action="Review tool usage pattern and implement tool chaining policies"
        )

    def evaluate(self, tool_call: MCPToolCall, history: List[MCPToolCall]) -> Optional[DetectionAlert]:
        # Get recent tool calls from same agent (last 5 minutes)
        recent_calls = [
            h for h in history
            if h.agent_id == tool_call.agent_id and
            (tool_call.timestamp - h.timestamp).total_seconds() < 300
        ]

        recent_tools = [c.tool_name for c in recent_calls]
        current_tool = tool_call.tool_name

        # Check for dangerous chains
        for source_tools, sink_tools in self.DANGEROUS_CHAINS:
            if current_tool in sink_tools:
                if any(source in recent_tools for source in source_tools):
                    return DetectionAlert(
                        rule_id=self.rule_id,
                        rule_name=self.rule_name,
                        severity=self.severity,
                        description=f"Suspicious tool chain: {' → '.join(recent_tools[-3:])} → {current_tool}",
                        evidence=[
                            f"Recent tools: {', '.join(recent_tools)}",
                            f"Current tool: {current_tool}",
                            f"Pattern: data access → exfiltration/execution",
                            f"Time window: 5 minutes"
                        ],
                        affected_component=tool_call.agent_id,
                        recommended_action=self.recommended_action,
                        metadata={
                            "tool_chain": recent_tools + [current_tool],
                            "chain_length": len(recent_tools) + 1
                        }
                    )

        return None


class BulkDataAccessRule(DetectionRule):
    """Detect bulk data access patterns"""

    def __init__(self):
        super().__init__(
            rule_id="MCP-005",
            rule_name="Bulk Data Access Detection",
            severity=DetectionSeverity.HIGH,
            description="Detected bulk data access that may indicate data exfiltration",
            recommended_action="Investigate data access purpose and implement DLP controls"
        )

    def evaluate(self, tool_call: MCPToolCall, history: List[MCPToolCall]) -> Optional[DetectionAlert]:
        # Check for database queries with large limits
        if 'database' in tool_call.tool_name.lower() or 'query' in tool_call.tool_name.lower():
            limit = tool_call.parameters.get('limit', 0)
            if limit > 1000:
                return DetectionAlert(
                    rule_id=self.rule_id,
                    rule_name=self.rule_name,
                    severity=self.severity,
                    description=f"Bulk database query with limit {limit}",
                    evidence=[
                        f"Query limit: {limit}",
                        f"Tool: {tool_call.tool_name}",
                        f"Agent: {tool_call.agent_id}"
                    ],
                    affected_component=tool_call.agent_id,
                    recommended_action=self.recommended_action,
                    metadata={"limit": limit}
                )

        # Check for multiple rapid file reads
        recent_reads = [
            h for h in history
            if h.agent_id == tool_call.agent_id and
            'read' in h.tool_name.lower() and
            (tool_call.timestamp - h.timestamp).total_seconds() < 60
        ]

        if len(recent_reads) > 10:
            return DetectionAlert(
                rule_id=self.rule_id,
                rule_name=self.rule_name,
                severity=self.severity,
                description=f"Rapid file access: {len(recent_reads)} files in 1 minute",
                evidence=[
                    f"Files accessed: {len(recent_reads)}",
                    f"Time window: 1 minute",
                    f"Agent: {tool_call.agent_id}"
                ],
                affected_component=tool_call.agent_id,
                recommended_action=self.recommended_action,
                metadata={"file_count": len(recent_reads)}
            )

        return None


class PromptInjectionInParametersRule(DetectionRule):
    """Detect prompt injection attempts in tool parameters"""

    INJECTION_KEYWORDS = [
        'ignore previous instructions',
        'disregard previous',
        'forget all previous',
        'new instructions',
        'system:',
        '[SYSTEM]',
        '<|im_start|>',
        'you are now',
        'override your'
    ]

    def __init__(self):
        super().__init__(
            rule_id="MCP-006",
            rule_name="Prompt Injection in Parameters",
            severity=DetectionSeverity.CRITICAL,
            description="Detected prompt injection attempt in tool parameters",
            recommended_action="Block request and investigate for injection attack"
        )

    def evaluate(self, tool_call: MCPToolCall, history: List[MCPToolCall]) -> Optional[DetectionAlert]:
        # Check all string parameters
        for key, value in tool_call.parameters.items():
            if isinstance(value, str):
                value_lower = value.lower()
                for keyword in self.INJECTION_KEYWORDS:
                    if keyword in value_lower:
                        return DetectionAlert(
                            rule_id=self.rule_id,
                            rule_name=self.rule_name,
                            severity=self.severity,
                            description=f"Prompt injection keyword detected in '{key}' parameter",
                            evidence=[
                                f"Parameter: {key}",
                                f"Keyword: {keyword}",
                                f"Value preview: {value[:100]}...",
                                f"Tool: {tool_call.tool_name}"
                            ],
                            affected_component=tool_call.agent_id,
                            recommended_action=self.recommended_action,
                            metadata={
                                "parameter": key,
                                "keyword": keyword,
                                "value_length": len(value)
                            }
                        )

        return None


class MCPDetectionEngine:
    """Main detection engine for MCP tool usage"""

    def __init__(self):
        self.rules: List[DetectionRule] = [
            SensitiveFileAccessRule(),
            PathTraversalRule(),
            CommandInjectionRule(),
            ToolChainingRule(),
            BulkDataAccessRule(),
            PromptInjectionInParametersRule()
        ]
        self.history: List[MCPToolCall] = []
        self.alerts: List[DetectionAlert] = []
        logger.info("MCP Detection Engine initialized", rule_count=len(self.rules))

    def analyze_tool_call(self, tool_call: MCPToolCall) -> List[DetectionAlert]:
        """
        Analyze tool call against all detection rules

        Args:
            tool_call: MCP tool call to analyze

        Returns:
            List of triggered alerts
        """
        alerts = []

        for rule in self.rules:
            try:
                alert = rule.evaluate(tool_call, self.history)
                if alert:
                    alerts.append(alert)
                    self.alerts.append(alert)
                    logger.warning(
                        "Detection rule triggered",
                        rule_id=rule.rule_id,
                        rule_name=rule.rule_name,
                        severity=alert.severity.value,
                        agent=tool_call.agent_id
                    )
            except Exception as e:
                logger.error("Rule evaluation failed", rule_id=rule.rule_id, error=str(e))

        # Add to history
        self.history.append(tool_call)

        # Keep history size manageable (last 1000 calls)
        if len(self.history) > 1000:
            self.history = self.history[-1000:]

        return alerts

    def get_alerts_by_severity(self, severity: DetectionSeverity) -> List[DetectionAlert]:
        """Get all alerts of a specific severity"""
        return [a for a in self.alerts if a.severity == severity]

    def get_alerts_by_agent(self, agent_id: str) -> List[DetectionAlert]:
        """Get all alerts for a specific agent"""
        return [a for a in self.alerts if a.affected_component == agent_id]

    def clear_history(self):
        """Clear tool call history and alerts"""
        self.history.clear()
        self.alerts.clear()
        logger.info("Detection engine history cleared")
